  - name: Submodule Sync
  # You may pin to the exact commit or the version.
  # uses: mheap/submodule-sync-action@a06903a4e38f042f6f52cc88d184ec1c930ee12d
  uses: mheap/submodule-sync-action@v1
  with:
    # The GitHub API token to use
    token: # optional, default is ${{ github.token }}
    # The path in the repo to update
    path: Overlays/TerminalChat
    # The branch name to check for updates in the remote repo
    ref: main
    # The name of the branch to use when creating a pull request
    pr_branch: main
    # The name of the branch that the PR should be raised against
    target_branch: main
    # The name of the branch that the PR should be based on
    base_branch:
    # Text to include in the generated PR's description
    pr_body: # optional, default is 
    # The labels that the PR will have, newline-seperated
    pr_labels: # optional, default is 
          
